[alias]
dev = "run -p game_runtime --features dev_tools,bevy/dynamic_linking,bevy/file_watcher"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
