# インフラCIのGitHub Actionsワークフロー。これは手動でトリガーされ、インフラテストとオプションでデプロイを実行する。さらに、CDK Nagの警告を抑制するためのコメントも含まれている。
name: Infra CI (manual)

on:
  workflow_dispatch:
    inputs:
      run_deploy:
        description: Also run deploy after tests pass
        required: false
        type: boolean
        default: false

jobs:
  infra-test:
    uses: ./.github/workflows/infra-test-job.yml
    with:
      cdk_env: ${{ vars.CDK_ENV }}
      cdk_default_account: ${{ vars.CDK_DEFAULT_ACCOUNT }}
      github_owner: ${{ github.repository_owner }}
      github_repo: ${{ github.event.repository.name }}

  infra-deploy:
    needs: infra-test
    if: inputs.run_deploy
    uses: ./.github/workflows/infra-deploy-job.yml
    with:
      cdk_env: ${{ vars.CDK_ENV }}
      cdk_default_account: ${{ vars.CDK_DEFAULT_ACCOUNT }}
      aws_region: ${{ vars.AWS_REGION }}
      github_owner: ${{ github.repository_owner }}
      github_repo: ${{ github.event.repository.name }}
      github_branch: ${{ github.ref_name }}
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
